/**
 * Declarative config for admin CRUD modules. Each resource maps to a backend
 * content collection with the shared CRUD shape (list/detail/create/update/status/delete).
 *
 * Field types: text, textarea, richtext, number, select, checkbox, tags, date,
 * image, images, documents, seo, object (nested fields), category (async select), url
 */
const seo = { name: 'seo', type: 'seo', label: 'SEO' };
const status = (values = ['draft', 'published', 'archived']) => ({ name: 'status', type: 'select', label: 'Status', options: values });
const sortOrder = { name: 'sortOrder', type: 'number', label: 'Sort order' };

export const RESOURCES = {
  products: {
    label: 'Products',
    singular: 'Product',
    endpoint: '/products',
    slugField: 'name',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'productCode', label: 'Code' },
      { key: 'casNumber', label: 'CAS' },
      { key: 'categoryId.name', label: 'Category' },
      { key: 'featured', label: 'Featured', type: 'bool' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    statuses: ['draft', 'published', 'archived'],
    fields: [
      { name: 'name', type: 'text', label: 'Product name', required: true },
      { name: 'slug', type: 'text', label: 'Slug', hint: 'Leave blank to auto-generate from name' },
      { name: 'productCode', type: 'text', label: 'Product code' },
      { name: 'casNumber', type: 'text', label: 'CAS number', hint: 'Format: 1234-56-7' },
      { name: 'categoryId', type: 'category', label: 'Category', required: true },
      { name: 'therapeuticArea', type: 'text', label: 'Therapeutic area' },
      { name: 'shortDescription', type: 'textarea', label: 'Short description', max: 500 },
      { name: 'description', type: 'richtext', label: 'Description', hint: 'Required to publish. Only client-approved content.' },
      { name: 'applications', type: 'tags', label: 'Applications' },
      {
        name: 'technicalInformation',
        type: 'object',
        label: 'Technical information',
        fields: [
          { name: 'molecularFormula', type: 'text', label: 'Molecular formula' },
          { name: 'molecularWeight', type: 'text', label: 'Molecular weight' },
          { name: 'grade', type: 'text', label: 'Grade' },
          { name: 'purity', type: 'text', label: 'Purity / Assay' },
          { name: 'appearance', type: 'text', label: 'Appearance' },
          { name: 'storageConditions', type: 'text', label: 'Storage conditions' },
          { name: 'packaging', type: 'text', label: 'Packaging' },
          { name: 'shelfLife', type: 'text', label: 'Shelf life' },
        ],
      },
      { name: 'image', type: 'image', label: 'Main image' },
      { name: 'gallery', type: 'images', label: 'Gallery images' },
      { name: 'documents', type: 'documents', label: 'Documents (brochures, spec sheets)' },
      { name: 'featured', type: 'checkbox', label: 'Featured on home page' },
      sortOrder,
      status(),
      seo,
    ],
  },
  categories: {
    label: 'Categories',
    singular: 'Category',
    endpoint: '/categories',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'slug', label: 'Slug' },
      { key: 'sortOrder', label: 'Order' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    statuses: ['active', 'inactive'],
    fields: [
      { name: 'name', type: 'text', label: 'Name', required: true },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'description', type: 'textarea', label: 'Description' },
      { name: 'image', type: 'image', label: 'Image' },
      sortOrder,
      status(['active', 'inactive']),
      seo,
    ],
  },
  capabilities: {
    label: 'Capabilities',
    singular: 'Capability',
    endpoint: '/capabilities',
    columns: [{ key: 'title', label: 'Title' }, { key: 'sortOrder', label: 'Order' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'title', type: 'text', label: 'Title', required: true },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'summary', type: 'textarea', label: 'Summary', max: 500 },
      { name: 'description', type: 'richtext', label: 'Description' },
      { name: 'icon', type: 'select', label: 'Icon', options: ['flask', 'shield', 'factory', 'file', 'globe', 'check'] },
      { name: 'highlights', type: 'tags', label: 'Highlights' },
      { name: 'images', type: 'images', label: 'Images' },
      sortOrder,
      status(),
      seo,
    ],
  },
  certifications: {
    label: 'Certifications',
    singular: 'Certification',
    endpoint: '/certifications',
    columns: [{ key: 'name', label: 'Name' }, { key: 'authority', label: 'Authority' }, { key: 'expiresAt', label: 'Expires', type: 'date' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'name', type: 'text', label: 'Certification name', required: true },
      { name: 'authority', type: 'text', label: 'Issuing authority' },
      { name: 'certificateNumber', type: 'text', label: 'Certificate number' },
      { name: 'description', type: 'textarea', label: 'Description', hint: 'Only verifiable, client-supplied claims.' },
      { name: 'issuedAt', type: 'date', label: 'Issued on' },
      { name: 'expiresAt', type: 'date', label: 'Valid until' },
      { name: 'image', type: 'image', label: 'Logo / badge' },
      { name: 'document', type: 'document', label: 'Certificate PDF' },
      sortOrder,
      status(),
    ],
  },
  facilities: {
    label: 'Facilities',
    singular: 'Facility',
    endpoint: '/facilities',
    columns: [{ key: 'name', label: 'Name' }, { key: 'location', label: 'Location' }, { key: 'type', label: 'Type' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'name', type: 'text', label: 'Facility name', required: true },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'location', type: 'text', label: 'Location' },
      { name: 'type', type: 'text', label: 'Type', hint: 'e.g. Manufacturing, R&D, Warehouse' },
      { name: 'summary', type: 'textarea', label: 'Summary', max: 500 },
      { name: 'description', type: 'richtext', label: 'Description' },
      { name: 'highlights', type: 'tags', label: 'Highlights' },
      { name: 'images', type: 'images', label: 'Images' },
      sortOrder,
      status(),
      seo,
    ],
  },
  leadership: {
    label: 'Leadership',
    singular: 'Leader',
    endpoint: '/leadership',
    columns: [{ key: 'name', label: 'Name' }, { key: 'designation', label: 'Designation' }, { key: 'sortOrder', label: 'Order' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'name', type: 'text', label: 'Name', required: true },
      { name: 'designation', type: 'text', label: 'Designation', required: true },
      { name: 'biography', type: 'richtext', label: 'Biography' },
      { name: 'photo', type: 'image', label: 'Photo' },
      { name: 'linkedinUrl', type: 'url', label: 'LinkedIn URL' },
      { name: 'email', type: 'text', label: 'Email (optional, public)' },
      sortOrder,
      status(),
    ],
  },
  news: {
    label: 'News & Events',
    singular: 'Article',
    endpoint: '/news',
    columns: [{ key: 'title', label: 'Title' }, { key: 'type', label: 'Type' }, { key: 'publishedAt', label: 'Published', type: 'date' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'title', type: 'text', label: 'Title', required: true },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'type', type: 'select', label: 'Type', options: ['news', 'event', 'press-release'] },
      { name: 'summary', type: 'textarea', label: 'Summary', max: 500 },
      { name: 'content', type: 'richtext', label: 'Content' },
      { name: 'featuredImage', type: 'image', label: 'Featured image' },
      { name: 'eventDate', type: 'date', label: 'Event date (events only)' },
      { name: 'eventLocation', type: 'text', label: 'Event location' },
      { name: 'publishedAt', type: 'date', label: 'Publish date', hint: 'Defaults to now when published' },
      status(),
      seo,
    ],
  },
  careers: {
    label: 'Careers',
    singular: 'Vacancy',
    endpoint: '/careers',
    columns: [{ key: 'title', label: 'Title' }, { key: 'department', label: 'Department' }, { key: 'location', label: 'Location' }, { key: 'closingDate', label: 'Closes', type: 'date' }, { key: 'status', label: 'Status', type: 'status' }],
    statuses: ['draft', 'open', 'closed', 'archived'],
    fields: [
      { name: 'title', type: 'text', label: 'Job title', required: true },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'department', type: 'text', label: 'Department' },
      { name: 'location', type: 'text', label: 'Location' },
      { name: 'employmentType', type: 'select', label: 'Employment type', options: ['Full-time', 'Part-time', 'Contract', 'Internship'] },
      { name: 'experience', type: 'text', label: 'Experience', hint: 'e.g. 2–4 years' },
      { name: 'qualification', type: 'text', label: 'Qualification' },
      { name: 'description', type: 'richtext', label: 'Description' },
      { name: 'responsibilities', type: 'tags', label: 'Responsibilities' },
      { name: 'requirements', type: 'tags', label: 'Requirements' },
      { name: 'closingDate', type: 'date', label: 'Closing date' },
      status(['draft', 'open', 'closed', 'archived']),
      seo,
    ],
  },
  gallery: {
    label: 'Gallery',
    singular: 'Gallery item',
    endpoint: '/gallery',
    columns: [{ key: 'image', label: 'Image', type: 'image' }, { key: 'title', label: 'Title' }, { key: 'category', label: 'Category' }, { key: 'status', label: 'Status', type: 'status' }],
    fields: [
      { name: 'title', type: 'text', label: 'Title', required: true },
      { name: 'image', type: 'image', label: 'Image', required: true },
      { name: 'category', type: 'text', label: 'Category', hint: 'e.g. Facilities, Events, Team' },
      { name: 'caption', type: 'textarea', label: 'Caption' },
      sortOrder,
      status(),
    ],
  },
};

export const getPath = (obj, path) => path.split('.').reduce((o, k) => (o == null ? undefined : o[k]), obj);
